### PR TITLE
Refactor Properties.isRandomDNA(String) - Issue #73

### LINKED ISSUE #73: Refactor Properties.isRandomDNA(String)
I've selected [**Properties.isRandomDNA(String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/Properties.java#L153-L165) for refactoring, which is a unit of **9** lines of code and **5** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by B4CKF1SH**
Changed calculation to compare max and min value instead of all values, reducing complexity.

Closes #73

### CODE REVIEW

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
The code looks fine but when it is tested on dnalong.fa, it doesn't say that it is random, even though it is. Could you please look into this? Thanks!

**Comment by Verisimilitude11** [comment]
@B4CKF1SH

**Comment by Speedro** [comment]
@B4CKF1SH Intellij Idea marks that the method is no longer used but remains in the code, I believe it can be deleted and this PR closed.

**Comment by Verisimilitude11** [comment]
Good catch @Speedro! I didn't realize that this method call got deleted. I'll be adding it back promptly.

**Comment by Speedro** [comment]
> Good catch @Speedro! I didn't realize that this method call got deleted. I'll be adding it back promptly.

we need to add the unit tests :)

**Comment by Verisimilitude11** [comment]
> 

Yes, exactly. I'll be working on that this weekend. That is unless you want to help!

**Comment by Speedro** [comment]
> > 
> 
> Yes, exactly. I'll be working on that this weekend. That is unless you want to help!

sure I can help, but I can start tomorrow if thats ok :)

**Comment by B4CKF1SH** [comment]
The issue was a missing pair of brackets, messing up the calculations in the new method. I added a fix, it now correctly identifies dnalong.fa. Please let me know if any further changes are required.

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Looks good @B4CKF1SH! Could you please elaborate further on how you simplified the code in the comments?

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Looks perfect now! I'll merge it once you clear the merge conflicts.

**Comment by Verisimilitude11** [comment]
> Looks perfect now! I'll merge it once you clear the merge conflicts.

@B4CKF1SH

**Comment by Verisimilitude11** [comment]
Hey @boaglio, I will be out of office for some time, so it will take me some time merge the pull request. However, I will approve the pull request once you clear the merge conflicts, in case you are participating in Hacktoberfest. Thanks for working on this, we at DNAnalyzer really appreciate your help!

**Comment by Verisimilitude11** [comment]
@B4CKF1SH please clear merge conflicts! I'll approve your PR once you do so.

**Comment by B4CKF1SH** [comment]
I fixed the conflicts on my fork, it should be good now.

**Review by Verisimilitude11 — APPROVED** [review]
Looks great @B4CKF1SH. Sorry for the delay in approving this PR!

**Comment by Verisimilitude11** [comment]
Looking forward to seeing more PRs from you on DNAnalyzer!

**Pull request merged**
