### PR TITLE
removed instantiation of class with only static methods

### PR DESCRIPTION
**Pull request by AbbasSalloum**
#170

### CODE REVIEW

**Review by Verisimilitude11 — APPROVED** [review]

**Comment by AbbasSalloum** [comment]
Hello,

Is there an issue with this PR? What action items are left to close this PR?

Please advise.

Cheers

**Comment by Verisimilitude11** [comment]
> Hello,
> 
> Is there an issue with this PR? What action items are left to close this PR?
> 
> Please advise.
> 
> Cheers

No, it looks good, I was just waiting for the checks to complete. I'm merging it now.

**Comment by Verisimilitude11** [comment]
@AbbasSalloum please star the repository if you haven't already.

**Comment by AbbasSalloum** [comment]
Ok great starred

**Comment by Verisimilitude11** [comment]
Alright, thank you so much! Looking forward to working with you in the coming weeks.

**Pull request merged**
