### PR TITLE
Refactor getAminoAcid

### LINKED ISSUE #78: Refactor CodonData.getAminoAcid(AminoAcidNames)
I've selected [**CodonData.getAminoAcid(AminoAcidNames)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/CodonData.java#L68-L92) for refactoring, which is a unit of **25** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by shubhwip**
closes #78

### CODE REVIEW

**Comment by shubhwip** [comment]
@Verisimilitude11 Please review.

**Comment by Verisimilitude11** [comment]
It's getting a bit late for me today (I'm in the US right now), so I'll approve it tomorrow (in <12 hours). Thanks for the PR!

**Comment by androlover98** [comment]
This should also fix #75 @Verisimilitude11

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Hi @shubhwip sorry I got to this PR last. Could you please resolve the conflicts? Thanks for your help so far!

**Comment by shubhwip** [comment]
> Hi @shubhwip sorry I got to this PR last. Could you please resolve the conflicts? Thanks for your help so far!

Please review.

**Review by Verisimilitude11 — APPROVED** [review]

**Pull request merged**
