### PR TITLE
Refactor CodonData class #69

### LINKED ISSUE #69: Refactor CodonData.java
I've selected [**CodonData.java**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/CodonData.java#L1-L93) for refactoring, which is a module of **55** lines of code and **21** incoming calls. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Separate Concerns in Modules** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Avoid large modules with high fan-in (nr. of incoming calls).
- **Why**❓ 
This keeps the codebase loosely coupled which makes it easier to minimize the consequences of changes.
- **How** 🔧 
Identify and extract responsibilities of large modules into smaller ones and hide implementation details behind interfaces. Target having modules that have no more than 10 incoming calls.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by shubhwip**
Rename class CodonData to CodonDataUtils
Update docs
closes #69

### CODE REVIEW

**Review by Verisimilitude11 — APPROVED** [review]
Looks good!

**Comment by Verisimilitude11** [comment]
@shubhwip seems like there are some conflicts. Could you please try to resolve those? Thanks!

**Review by Verisimilitude11 — APPROVED** [review]
Looks good!

**Comment by shubhwip** [comment]
@Verisimilitude11 Please revert this and merge the latest PR.

**Pull request merged**
