### PR TITLE
Refactor CodonDataConstants

### LINKED ISSUE #190: Refactor CodonDataConstants.$block1
I've selected [**CodonDataConstants.$block1**](https://github.com/Verisimilitude11/DNAnalyzer/blob/43151e8f70d86b468dc676c3f5e3f1bc7a4bdca3/src/main/java/DNAnalyzer/CodonDataConstants.java#L62-L112) for refactoring, which is a unit of **47** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by Kit-p**
Removed static initializer in favor of inline initialization.

Closes #190.

### CODE REVIEW

**Comment by Kit-p** [comment]
@Verisimilitude11 Looks like still fails the Better Code Hub check, but I think it is acceptable in this specific context.

**Comment by Verisimilitude11** [comment]
> @Verisimilitude11 Looks like still fails the Better Code Hub check, but I think it is acceptable in this specific context.

Yeah, it should be good. BetterCodeHub's checks honestly aren't that useful anyway.

**Comment by Verisimilitude11** [comment]
I'll approve it once I do some additional testing later today. Thanks so much for working on this!

**Review by Verisimilitude11 — APPROVED** [review]

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Could you please clear the merge conflicts? Thanks @Kit-p!

**Comment by Kit-p** [comment]
@Verisimilitude11 Resolved. Please review again, thank you!

**Comment by Verisimilitude11** [comment]
Hey @Kit-p, I will be out of office for some time, so it will take me some time merge the pull request. However, I will approve the pull request in case you are participating in Hacktoberfest. Thanks for working on this, we at DNAnalyzer really appreciate your help!

**Review by Verisimilitude11 — APPROVED** [review]

**Comment by Kit-p** [comment]
@Verisimilitude11 No worry, thanks a lot!
By the way, if you have some refactoring tasks left open for too long, you can ping me, I can work on those as well.

**Comment by Verisimilitude11** [comment]
Sounds great, will do! 👍🎉

**Comment by Verisimilitude11** [comment]
By the way, are you participating in Hacktoberfest?

**Comment by Kit-p** [comment]
> By the way, are you participating in Hacktoberfest?

Yeah, completed with a tree :D

**Pull request merged**
