### PR TITLE
Count base pairs update

### PR DESCRIPTION
**Pull request by garyglatfelter**
Continuation of PR  Count base pairs #240 which I closed by accident somehow.
This fixes Verisimilitude11/DNAnalyzer #103

### CODE REVIEW

**Comment by garyglatfelter** [comment]
@Verisimilitude11 Regarding https://github.com/Verisimilitude11/DNAnalyzer/pull/240#pullrequestreview-1154037230

Hmm. I see.
CmdArgs calls DnaAnalyzer.printProteins() which calls printProteinList() which then calls Properties.printNucleotideCount(). The count you are seeing is generated from Properties.printNucelotideCount().

A potential solution is to replace the call to countNucleotides() in Properties.printNucleotideCount(), replacing it with a call to the newly introduced DnaAnalyzer.countBasePairsStream().

Currently, countNucleotides() is only used there and in Properties.isRandomDNA() which I've updated. I do not see countNucelotides() used anywhere else in the project so I believe that could be safely deleted.

**Comment by Verisimilitude11** [comment]
Sounds good @garyglatfelter, thanks for the quick update! Let me know once you implement these:
>A potential solution, and the route that seemed simplest to me, is to replace the call to countNucleotides() in Properties.printNucleotideCount(), replacing it with a call to the newly introduced DnaAnalyzer.countBasePairs().

> I do not see countNucelotides() used anywhere else in the project so I believe that can be safely deleted.
Thanks again for taking the maintainability of the code into consideration.

**Comment by garyglatfelter** [comment]
@Verisimilitude11  Already done :). I just figured I would roll it back if you said no. It's all set for review.

**Comment by Verisimilitude11** [comment]
Alright, thanks! Looks like there's a couple merge conflicts - could you please fix those as well?

**Comment by garyglatfelter** [comment]
@Verisimilitude11 try now please

**Review by Verisimilitude11 — APPROVED** [review]
Wow @garyglatfelter, I can see how fast the code has become with this one change without running any time tests! Let's work on implementing parallel stream in as many methods as possible.

**Pull request merged**
