### PR TITLE
Add Rating GUI

### LINKED ISSUE #332: Add user feedback tools to DNAnalyzer
DNAnalyzer should include tools for gathering user feedback, such as rating systems or feedback forms, to help improve the software based on the needs and preferences of its users. This could include a system for users to rate the software or leave comments and suggestions. User feedback tools would allow us to better understand how users are using DNAnalyzer and what they would like to see added or improved in future updates.

### PR DESCRIPTION
**Pull request by Ravina-Deogadkar**
Attached demo video to issue #332.

Closes #332

### CODE REVIEW

**Review by LimesKey — COMMENTED** [review]
Maybe we can merge this into a seperate branch until we can get the DB working for the responses?

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Hey @Ravina-Deogadkar, I'm getting this error after clicking on "Rate us":
image

**Comment by Verisimilitude11** [comment]
> Maybe we can merge this into a seperate branch until we can get the DB working for the responses?

Sure, but that'd result in a lot of merge conflicts down the road.

**Comment by Ravina-Deogadkar** [comment]
> Hey @Ravina-Deogadkar, I'm getting this error after clicking on "Rate us": image

Sure I'll check that..

**Comment by Ravina-Deogadkar** [comment]
> > Hey @Ravina-Deogadkar, I'm getting this error after clicking on "Rate us": image
> 
> Not reproducing on my machine

Fixed It!.. Sorry I missed it..

**Review by Verisimilitude11 — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
