### PR TITLE
Count base pairs

### PR DESCRIPTION
**Pull request by garyglatfelter**
I couldn't get JUnit to work with gradle configuration. I changed it to use more recent JUnit 5. I hope that is ok.

Also, would you like null Strings passed as argument to throw exception or just return 0 for base pairs counts? I chose to return 0 but I can change that if you'd like.

### CODE REVIEW

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
@garyglatfelter looks like there are some conflicts with src/main/java/DNAnalyzer/DnaAnalyzer.java. Could you please look into that? If you aren't able to, I would recommend copying over the file currently in the main, re-editing the file, and then pushing again.

**Comment by Verisimilitude11** [comment]
@garyglatfelter wow your stream is a lot faster than the array, even for just counting the base pairs: 
image

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
There seems to be a bug, @garyglatfelter. When I run it from CmdArgs (lines 79-86), it says 0 for AT and GC, respectively. 
image
Could you please look into this? Thanks! Once we get this fixed, I'll merge the PR. You can remove the classic Array method as the Parallel Stream appears to be significantly faster, at least on my machine. Let me know what your thoughts on this are.

**Comment by Verisimilitude11** [comment]
@garyglatfelter why did you close this PR? Is there anything I can do to help?

**Comment by garyglatfelter** [comment]
ah, no, I'm just struggling with git. I'm not sure how to merge the DNAnalyzer main into my main without conflicts. I just reset it to match the upstream and merged the branch again. I'm not sure why it closed.

**Comment by Verisimilitude11** [comment]
Oh I see, no worries. By the way, would you like to join our Discord server to communicate more efficiently? https://github.com/Verisimilitude11/DNAnalyzer/discussions/256

**Pull request closed without merging**
