### PR TITLE
Adds a background video to the website

### PR DESCRIPTION
**Pull request by ArchontisKostis**
This commit adds a background video on the website of DNAnalyzer. I hope you like it!

Video by Pressmaster from Pexels: https://www.pexels.com/video/digital-formation-of-a-dna-in-an-animated-presentation-3191572/

### CODE REVIEW

**Review by LimesKey — CHANGES_REQUESTED** [review]
I love it! It looks really good and makes the text look so much better. Are you just able to rename the video.mp4 file to something like "dna_spiral.mp4" and move the file into the "assets" folder to make it more organized?

**Comment by ArchontisKostis** [comment]
Done! 😉
If there is anything else I can do, feel free to tell me!

**Review by LimesKey — APPROVED** [review]
Looks great!

**Review by Verisimilitude11 — APPROVED** [review]
Looks awesome @ArchontisKostis, I love the new aesthetic! @LimesKey thanks for reviewing the PR while I was gone 😅

**Pull request merged**
