### PR TITLE
Reverse option

### PR DESCRIPTION
**Pull request by Nv7-GitHub**
This allows the user to reverse the DNA before processing it, through the `-r` or `--reverse` command-line argument.

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
Solves #10

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Looks great! Can you update the documentation and --help

**Comment by Verisimilitude11** [comment]
> Looks great! Can you update the documentation and --help

@Nv7-GitHub

**Review by Verisimilitude11 — APPROVED** [review]

**Comment by Nv7-GitHub** [comment]
@Verisimilitude11 updated README

**Review by Verisimilitude11 — APPROVED** [review]

**Pull request merged**
