### PR TITLE
resolves #80: Refactor CoreExecutor.createProteinList(String,String)

### LINKED ISSUE #80: Refactor CoreExecutor.createProteinList(String,String)
I've selected [**CoreExecutor.createProteinList(String,String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/CoreExecutor.java#L79-L105) for refactoring, which is a unit of **27** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by iamHrithikRaj**
Refactored `CoreExecutor.createProteinList(String,String)`.
Removed the logic of passing down the amino acids as args to the `getProtein(String, String)` function and use `CodonData.getAminoAcid()` in `getProtein(String, String)` itself for better encapsulation.

### CODE REVIEW

**Comment by iamHrithikRaj** [comment]
resolved conflicts!

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Looks good! Could you please fix the conflicts? Thanks!

**Comment by iamHrithikRaj** [comment]
> Looks good! Could you please fix the conflicts? Thanks!

done already

**Comment by Verisimilitude11** [comment]
> > Looks good! Could you please fix the conflicts? Thanks!
> 
> done already

Yes, sorry, I think you made the changes right when I was looking at it 😆. I'll do some testing quickly and will approve it!

**Comment by Verisimilitude11** [comment]
In the meantime, feel free to add yourself as an @author to the methods that you changed/added!

**Review by Verisimilitude11 — APPROVED** [review]
👍👍

**Comment by iamHrithikRaj** [comment]
> In the meantime, feel free to add yourself as an @author to the methods that you changed/added!

appreciate it bro, but it's fine it was a minor refactoring after all :)

**Pull request merged**
