### PR TITLE
#79 refactor default caller

### LINKED ISSUE #79: Refactor CoreExecutor.defaultCaller()
I've selected [**CoreExecutor.defaultCaller()**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/CoreExecutor.java#L114-L159) for refactoring, which is a unit of **26** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by Speedro**
Closes #79 

Tried to split the logic to a separate class so the CoreExecutor is responsible for less things.

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
If #123 is merged I think we should move the CoreExecutor stuff into the `run` method in that class, which is how picocli recommends doing it. That way, the options are fields in the class instead of a parameter.

**Comment by Verisimilitude11** [comment]
@Nv7-GitHub can you open a separate issue for this? @Speedro feel free to open another PR that fixes it.

**Comment by Nv7-GitHub** [comment]
I think you can merge my PR and then the other PRs and then I can make a PR fixing things that are broken

**Comment by Verisimilitude11** [comment]
> I think you can merge my PR and then the other PRs and then I can make a PR fixing things that are broken

Sounds good!

**Comment by Speedro** [comment]
Hi @Nv7-GitHub and @Verisimilitude11. I've created a new issue for CoreExecutor class refactoring as @Nv7-GitHub suggested. Feel free to change the description and make more precise perhaps. The link to the issue is here #154

**Comment by Verisimilitude11** [comment]
> Hi @Nv7-GitHub and @Verisimilitude11. I've created a new issue for CoreExecutor class refactoring as @Nv7-GitHub suggested. Feel free to change the description and make more precise perhaps. The link to the issue is here #154

Thanks for that @Speedro! Could you please resolve the merge conflicts in this PR? Thanks!

**Comment by Nv7-GitHub** [comment]
Made #155, can you refactor `CmdArgs` once its merged instead?

**Comment by Speedro** [comment]
Ok, @Nv7-GitHub please let me know once the #155 is merged. Thanks 🚀

**Comment by Verisimilitude11** [comment]
> Ok, @Nv7-GitHub please let me know once the #155 is merged. Thanks 🚀 I'll rebase upon main afterwards.

#155 merged

**Comment by Verisimilitude11** [comment]
@Speedro merged gradle as well, you should be all set for refactoring

**Pull request closed without merging**
