### PR TITLE
Update CodonFrame.java

### PR DESCRIPTION
**Pull request by sourabhkashyap95**
Refactor CodonFrame.equals(Object) to reduce branch points. Removed unnecessary if condition by default assignment and having only one exit point from function.

Signed-off-by: Sourabh Kashyap <samsourabh95@gmail.com>

### CODE REVIEW

**Comment by Verisimilitude11** [comment]
Could you please resolve the conflicts @sourabhkashyap95. I'll approve and merge your PR once you do that. Thanks!

**Comment by Verisimilitude11** [comment]
@sourabhkashyap95 please clear merge conflicts! I'll approve your PR once you do so.

**Comment by sourabhkashyap95** [comment]
> Could you please resolve the conflicts @sourabhkashyap95. I'll approve and merge your PR once you do that. Thanks!

@Verisimilitude11 Resolved the merge conflicts.

**Comment by sourabhkashyap95** [comment]
Hi @Verisimilitude11 , can you please review and merge this PR?

**Comment by Verisimilitude11** [comment]
> Hi @Verisimilitude11 , can you please review and merge this PR?

Yes, I'll review it tomorrow. It is first in line on our backlog review. Thanks for contributing, and we're looking forward to seeing more PRs from you!

**Review by Verisimilitude11 — APPROVED** [review]

**Comment by Verisimilitude11** [comment]
@sourabhkashyap95 thanks for the PR. Remember to star this repository if you haven't done so already.

**Pull request merged**
