### PR TITLE
Feature/add javafx gui #121

### LINKED ISSUE #121: GUI

### PR DESCRIPTION
**Pull request by frankschmitt**
Implements a very basic GUI for DNAnalyzer (using JavaFX).

Closes #121.

So far, you can
- enter the name of the DNA file
- enter the name of the protein file
- set min and max
- start the analysis

Results are written to a text area in the GUI.

### CODE REVIEW

**Review by LimesKey — CHANGES_REQUESTED** [review]
I'm trying to run it from CMD for Windows, `./gradlew run --args="--gui"` does not seem to work, `'.' is not recognized as an internal or external command, operable program or batch file.`. Only `.\gradlew run --args="--gui"` works with the backslash.

I see here it says something about Java 19, do you need Java 19 for it to run or does it work with Java 17. Currently Gradle only supports Java 17 so everyone only downloads Java 17, I don't want to have to download Java 19 too. `javafx { version = "19"`

I am unable to run this and `.\gradlew build` fails. I'll try to do it again.

**Comment by frankschmitt** [comment]
> I'm trying to run it from CMD for Windows, `./gradlew run --args="--gui"` does not seem to work, `'.' is not recognized as an internal or external command, operable program or batch file.`. Only `.\gradlew run --args="--gui"` works with the backslash.

Aw sorry, stupid me - ./gradlew is UNIX / Linux syntax, whereas for Windows, it should indeed by .\gradlew or simply gradlew. I'll update the README accordingly.

> I see here it says something about Java 19, do you need Java 19 for it to run or does it work with Java 17. Currently Gradle only supports Java 17 so everyone only downloads Java 17, I don't want to have to download Java 19 too. `javafx { version = "19"`

That's the JavaFX version - running it with Java 17 works perfectly fine (in fact, I'm using OpenJDK 17.0.4 myself)
 
> I am unable to run this and `.\gradlew build` fails. I'll try to do it again.

**Comment by frankschmitt** [comment]
> > I am unable to run this and `.\gradlew build` fails. I'll try to do it again.

Should be fixed now - I've included a strategy for duplicate handling (I'm still not sure where the duplicate comes from, though - the file name mentioned in the error message (reflectionconfig.json) is totally unfamiliar to me. Might be a grade internal thingy)

**Comment by LimesKey** [comment]
Seems to get stuck at 80%? The GUI opens and the GUI looks really good so far though. 
image

**Comment by Verisimilitude11** [comment]
@frankschmitt could you please clear the merge conflicts? I'm really looking forward to testing the GUI later today! Thank you so much for working on this, I'll give you some feedback on it.

**Comment by frankschmitt** [comment]
> > I am unable to run this and `.\gradlew build` fails. I'll try to do it again.

Should be fixed now - I've included a strategy for duplicate handling (I'm still not sure where the duplicate comes from, though - the file name mentioned in the error message (reflectionconfig.json) is totally unfamiliar to me. Might be a grade internal thingy)


> @frankschmitt could you please clear the merge conflicts? I'm really looking forward to testing the GUI later today! Thank you so much for working on this, I'll give you some feedback on it after some testing.

I've synced the branch with main and resolved the merge conflicts - should be ok now.

**Review by LimesKey — DISMISSED** [review]
It looks really good so far, although it is still stuck at 80% in the CLI, the GUI still works and is responsive. 

I also get this message in the CLI everytime I click "Analyze"
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

Is it possible for you to make this the GUI launch from an executable file instead of the CLI? Most users are not comfortable with even touching the CLI for anything, so having this in a exe will make it a lot easier for beginners. 

Low priority, but are you also able to incorporate drag and drop functionality where it says "put filename in DNA file, and click analyze"? I'm very impressed though!

**Comment by LimesKey** [comment]
```
> Configure project :
Project : => no module-info.java found
```

**Comment by Verisimilitude11** [comment]
@frankschmitt, please clear conflicts as well. Thanks for implementing this btw!

**Comment by frankschmitt** [comment]
> It looks really good so far, although it is still stuck at 80% in the CLI, the GUI still works and is responsive.

I guess that's how "gradle run" works - it considers the task completed only when the program exits (i.e. when you close the GUI).

> I also get this message in the CLI everytime I click "Analyze"
> 
> ```
> Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> ```

That happens if you didn't set the DNA file - you have to enter the file name first. 

> 
> Is it possible for you to make this the GUI launch from an executable file instead of the CLI? Most users are not comfortable with even touching the CLI for anything, so having this in a exe will make it a lot easier for beginners.

AFAIK, the usual approach would be to provide a .cmd file for Windows and a .sh file for Linux / UNIX that uses the java executable to launch the application. Do you think that would suffice?

> Low priority, but are you also able to incorporate drag and drop functionality where it says "put filename in DNA file, and click analyze"? I'm very impressed though!

I'll create another issue for this. Implementing Drag & Drop is usually a little bit involved.

**Comment by frankschmitt** [comment]
> @frankschmitt, please clear conflicts as well. Thanks for implementing this btw!

I've updated the README and re-synced with the main branch - all conflicts should be resolved now.

**Comment by frankschmitt** [comment]
@Verisimilitude11 One more question regarding:

Verisimilitude11 removed the[ hacktoberfest-accepted ]

Is there a specific reason why you removed the hacktoberfest-accepted label?

**Comment by LimesKey** [comment]
Have you seen this? 
image
@frankschmitt

**Comment by Verisimilitude11** [comment]
>I guess that's how "gradle run" works - it considers the task completed only when the program exits (i.e. when you close the GUI).

Yeah, that's fine - it doesn't really matter.

>AFAIK, the usual approach would be to provide a .cmd file for Windows and a .sh file for Linux / UNIX that uses the java executable to launch the application. Do you think that would suffice?

Sure, could you please add that to your commit? Thanks!

>I'll create another issue for this. Implementing Drag & Drop is usually a little bit involved.
Sounds good. 👍 

>I've updated the README and re-synced with the main branch - all conflicts should be resolved now.
Awesome, I'm going to merge this then. You can add the .cmd and .sh file in another PR.

Regarding the hacktoberfest-accepted label, that was only for a PR challenge during the month of October. As October is now over, I removed the label. It has nothing to do with your PR - this is great!

**Comment by Verisimilitude11** [comment]
> Have you seen this? image @frankschmitt

@LimesKey, I will add separate issues for this - @frankschmitt doesn't need to fix them.

**Review by Verisimilitude11 — APPROVED** [review]

**Comment by Verisimilitude11** [comment]
@frankschmitt one thing, did you mark this as /TODO?

**Comment by Verisimilitude11** [comment]
I guess it would be helpful if @frankschmitt could take care of adding Javadocs is he gets time; no urgency. In the meantime, I'm going to merge this PR if it looks fine to you @LimesKey.

**Comment by LimesKey** [comment]
LGTM @Verisimilitude11

**Comment by Verisimilitude11** [comment]
> LGTM @Verisimilitude11

Can you please approve the PR?

**Review by LimesKey — APPROVED** [review]
LGTM

**Comment by frankschmitt** [comment]
> Regarding the hacktoberfest-accepted label, that was only for a PR challenge during the month of October. As October is now over, I removed the label. It has nothing to do with your PR - this is great!

Sorry to be a nuisance, but could you please re-add it? Because currently, the PR isn't counted for the Hacktoberfest challenge:

Screenshot from 2022-11-06 13-53-33

**Comment by frankschmitt** [comment]
> I guess it would be helpful if @frankschmitt could take care of adding Javadocs is he gets time; no urgency. In the meantime, I'm going to merge this PR if it looks fine to you @LimesKey.

I've added a new issues for this - https://github.com/Verisimilitude11/DNAnalyzer/issues/295. Can you please assign it to me?

**Comment by Verisimilitude11** [comment]
> > Regarding the hacktoberfest-accepted label, that was only for a PR challenge during the month of October. As October is now over, I removed the label. It has nothing to do with your PR - this is great!
> 
> Sorry to be a nuisance, but could you please re-add it? Because currently, the PR isn't counted for the Hacktoberfest challenge:
> 
> Screenshot from 2022-11-06 13-53-33

Sure, I added it back, no worries.

**Comment by Verisimilitude11** [comment]
> > I guess it would be helpful if @frankschmitt could take care of adding Javadocs is he gets time; no urgency. In the meantime, I'm going to merge this PR if it looks fine to you @LimesKey.
> 
> I've added a new issues for this - #295. Can you please assign it to me?

Done. Thanks for working on those, we really appreciate your help with the GUI!

**Pull request merged**
