### PR TITLE
Refactor ProteinFinder.getProtein with many args

### LINKED ISSUE #72: Refactor ProteinFinder.getProtein(String,String,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList)
I've selected [**ProteinFinder.getProtein(String,String,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/ProteinFinder.java#L26-L84) for refactoring, which is a unit of **42** lines of code and **23** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping related parameters into objects. Alternatively, try extracting parts of units that require fewer parameters.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by shubhwip**
Replace arraylist with list

Add constructor for ProteinFinder class

closes #72

### CODE REVIEW

**Comment by shubhwip** [comment]
@Verisimilitude11 Can you share Better Code Hub reports here ?

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Changes look fine, I'll approve both of your PRs once you clear your other PR's conflict

**Comment by Verisimilitude11** [comment]
> @Verisimilitude11 Can you share Better Code Hub reports here ?

image

**Comment by Verisimilitude11** [comment]
I'll approve this as well once the conflicts are resolved. Thank for taking the time to contribute to DNAnalyzer!

**Comment by shubhwip** [comment]
> I'll approve this as well once the conflicts are resolved. Thank for taking the time to contribute to DNAnalyzer!

Done

**Review by Verisimilitude11 — APPROVED** [review]
Nice work! Thanks for taking care of the conflicts.

**Pull request merged**
