### PR TITLE
added Contributing_Guidelines.md file

### PR DESCRIPTION
**Pull request by sumitbishti**

### CODE REVIEW

**Review by Verisimilitude11 — APPROVED** [review]
Looks great!

**Comment by Verisimilitude11** [comment]
Closes #83

**Comment by Verisimilitude11** [comment]
Could you please add a document for style guidelines as well, in a separate pull request? Thanks for your help!

**Comment by sumitbishti** [comment]
> Could you please add a document for style guidelines as well, in a separate pull request? Thanks for your help! @sumitbishti

Could you elaborate what type of style guidelines?

**Comment by Verisimilitude11** [comment]
> > Could you please add a document for style guidelines as well, in a separate pull request? Thanks for your help! @sumitbishti
> 
> Could you elaborate what type of style guidelines?

For example, tab instead of 4 spaces, style consistencies, etc. Here is an example of what I mean: 
https://github.com/Verisimilitude11/Mutorials/blob/master/CONTRIBUTING.md#indentation:~:text=Mutorials%20Code%20Conventions

**Comment by sumitbishti** [comment]
> > > Could you please add a document for style guidelines as well, in a separate pull request? Thanks for your help! @sumitbishti
> > 
> > 
> > Could you elaborate what type of style guidelines?
> 
> For example, tab instead of 4 spaces, style consistencies, etc. Here is an example of what I mean: https://github.com/Verisimilitude11/Mutorials/blob/master/CONTRIBUTING.md#indentation:~:text=Mutorials%20Code%20Conventions

I'm on it!

**Pull request merged**
