### PR TITLE
resolves #90: added and update java docs

### LINKED ISSUE #90: Check and Update Javadocs
**Describe the solution you'd like**
Verify that Javadocs match the class/method's purpose (@param and @return, description, etc. are accurate). If there are inconsistencies present, please update them. Additionally, please add more comments throughout the code as well as more details to the Javadocs.

**Additional context**
image

### PR DESCRIPTION
**Pull request by iamHrithikRaj**
- Added java doc for a few methods. 
- Did some inline documentation for unclear implementations
- Avoided documenting the obvious stuff

### CODE REVIEW

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Looks great! Could you please fix the conflicts? Thanks!

**Comment by iamHrithikRaj** [comment]
on it

**Comment by iamHrithikRaj** [comment]
conflict resolved!

**Review by Verisimilitude11 — APPROVED** [review]
Approved! Thanks for working on this.

**Pull request merged**
