### PR TITLE
Executable installer and GUI launcher

### PR DESCRIPTION
**Pull request by LimesKey**
I've created a PowerShell script and compiled it as an exe file to allow for easy use of the program. I've also added a very epic icon to the executable for an easier way to locate the file.

## Features:
- Automatic downloading of latest release of program
- Automatic Gradlew building 
- Automatic GUI Display
- Automatic compression and decompression of DNA asset files (coming soon)
- Automatic Java 17 installer (coming soon)
- Automatic Java PATH process  (coming soon)
- Config file for changing download location (coming soon)
- And more to come...
# 
This will only work on Windows and I have yet to test this on other computers than mine. You're free to compile the PowerShell script into an executable yourself, I used [ps2exe](https://github.com/MScholtes/PS2EXE) for the compile; I used another program called "[Resource Hacker](http://www.angusj.com/resourcehacker/)" for the cool icon. Feel free to help spice up the Powershell script, I know it's not super easy to read so I'd appreciate some help.

### CODE REVIEW

**Review by Verisimilitude11 — DISMISSED** [review]
@LimesKey what did you change in dnalong.fa? I'm asking because the changes are too large for me to view on github.com.

**Comment by LimesKey** [comment]
I replaced all of it with real random gene I found online and made it much much smaller

**Comment by Verisimilitude11** [comment]
Got it, sounds good!

**Review by Verisimilitude11 — APPROVED** [review]

**Comment by LimesKey** [comment]
@Verisimilitude11 oh my gosh, it feels like my birthday, I finally got merged!

**Comment by Verisimilitude11** [comment]
lol sorry i took way too much time to review this

**Comment by Verisimilitude11** [comment]
happy merge! 😅

**Comment by LimesKey** [comment]
@VerisimilitudeX will do, I'll also try reformatting the code for it to make it easier to read and incorporate best coding practises into it.

**Comment by VerisimilitudeX** [comment]
sounds great, thanks @LimesKey. I'll review your PR when it comes in

**Pull request merged**
