### PR TITLE
#187 - Refactor ProteinFinder

### LINKED ISSUE #187: Refactor ProteinFinder.getProtein(String,String)
I've selected [**ProteinFinder.getProtein(String,String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/43151e8f70d86b468dc676c3f5e3f1bc7a4bdca3/src/main/java/DNAnalyzer/ProteinFinder.java#L50-L84) for refactoring, which is a unit of **21** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by boaglio**
- removed properties and change to static class (ProteinFinder look like an Util class, not a Domain class)
- extracted one internal loop to a private method
- created some constants 
- changes some variable names to camel case standard

## Test

Successful test using parameters:

`--amino=histidine --max=5 --min=3 assets/dna/random/dnalong.fa`

Closes #187

### CODE REVIEW

**Comment by Verisimilitude11** [comment]
Hey @boaglio, I will be out of office for some time, so it will take me some time merge the pull request. However, I will approve the pull request in case you are participating in Hacktoberfest. Thanks for working on this, we at DNAnalyzer really appreciate your help!

**Review by Verisimilitude11 — APPROVED** [review]

**Comment by Verisimilitude11** [comment]
@boaglio could you please star this repository of you haven’t already.

**Comment by boaglio** [comment]
I did star already =)

**Comment by Verisimilitude11** [comment]
> I did star already =)

Thanks!

**Comment by Verisimilitude11** [comment]
@boaglio could you please clear the merge conflicts! I'll approve your PR once you do so.

**Pull request closed without merging**
