### PR TITLE
resolves #68 : updated README.md

### LINKED ISSUE #68: Update Docs to Reflect Current Code
Update README.md to reflect current features and add visuals to make it easier to understand/look good.

### PR DESCRIPTION
**Pull request by iamHrithikRaj**
resolves #68 : updated README.md with a video demo and commands to run the program

### CODE REVIEW

**Comment by iamHrithikRaj** [comment]
@Verisimilitude11 please review :)

**Review by Verisimilitude11 — APPROVED** [review]

**Comment by Verisimilitude11** [comment]
Seems like the video isn't working @iamHrithikRaj: 
image

**Comment by Verisimilitude11** [comment]
Actually, would it be possible for you to record another video using the new CLI? I'll host the video somewhere else and we can just put the link in through Markdown.

**Comment by iamHrithikRaj** [comment]
> Actually, would it be possible for you to record another video using the new CLI? I'll host the video somewhere else and we can just put the link in through Markdown.

sure, on it

**Comment by iamHrithikRaj** [comment]
@Verisimilitude11 I've sent you a mail on verisimilitude11@outlook.com with a GDrive link to the video.

**Comment by Verisimilitude11** [comment]
Received it, I'll host it on Azure and link it here. Thanks for redoing the video!

**Pull request merged**
