### PR TITLE
Configure Gradle build. Implements #117.

### LINKED ISSUE #117: Switch build to Gradle build tool
**Is your feature request related to a problem? Please describe.**
Currently, building / running the project can only be done by executing ```javac Main.java``` / ```java Main``` manually (or running Main from your IDE, e.g. Eclipse). This is especially confusing for new users, who are used to Maven or Gradle and simply wish to run 

```
gradle build
```

to build their project without having to worry about the dependencies etc.

Also, gradle allows publishing the package to Maven Central, running the tests etc. in a very straight-forward way.

**Describe the solution you'd like**
I'd like a project setup that allows the user to simply execute

```
gradle build
```

to build the project and 

```
gradle run
```

to run it.

**Describe alternatives you've considered**
An alternative to Gradle would be [Maven|https://maven.apache.org/]. Similar features, mostly a matter of preferences (personally, I prefer Gradle).

**Additional context**
If this sounds sensible to you, I'd be willing to implement it :-)

### PR DESCRIPTION
**Pull request by frankschmitt**
Configures a basic Gradle Java app build. To stick to Gradle convention as closely as possible, this commit
- adds several Gradle-specific directories / files to the git ignore list
- moves the source code from src/ to app/src/main/java/
- adds a (dummy) test class in app/src/test/java

It also updates the README and provides basic information on how to build + run the DNAnalyzer
(it seems that running the DNAnalyzer via "gradlew run" doesn't work so well, since Gradle uses STDIN / STDOUT itself - it kind of works, but it doesn't look good, so in the README, I only mentioned the classic "java -cp...." approach).

If the changed directory layout concerns you, I can revert the renaming of src/ and adapt the Gradle build.

Closes #117

### CODE REVIEW

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Looks great! If you think that reverting to `src/` wouldn't affect the Gradle build, could you please revert it? The additions looks great, I really appreciate your help!

**Comment by Verisimilitude11** [comment]
I'll approve this once you revert the directory change.

**Comment by Nv7-GitHub** [comment]
If this is merged after #123 can you get rid of the `picocli` folder and instead do https://picocli.info/#_add_as_external_dependency

**Comment by Verisimilitude11** [comment]
> If this is merged after #123 can you get rid of the `picocli` folder and instead do https://picocli.info/#_add_as_external_dependency

@frankschmitt

**Comment by frankschmitt** [comment]
> I'll approve this once you revert the directory change.

I've moved the source back to src, but kept the separate main/ and test/ subdirs - hope that's ok with you.

**Comment by Verisimilitude11** [comment]
Looks good @frankschmitt! I'll merge it later today after some testing.

**Review by Verisimilitude11 — APPROVED** [review]

**Comment by Verisimilitude11** [comment]
> 

@frankschmitt once I merge that PR, could you please create another PR with these changes? Thank you so much for your help thus far!

**Comment by Verisimilitude11** [comment]
@frankschmitt could you please resolve the conflict issues? If not, it's totally okay, it's just that I'll only be able to merge your PR on Friday after clearing the conflicts.

**Comment by frankschmitt** [comment]
> @frankschmitt could you please resolve the conflict issues? If not, it's totally okay, it's just that I'll only be able to merge your PR on Friday after clearing the conflicts.

I thought I had fixed this with my latest commit - sorry. I‘ll look into it on Thursday.

**Comment by Verisimilitude11** [comment]
> 

Sounds good

**Comment by Verisimilitude11** [comment]
Should I approve your changes?

**Comment by frankschmitt** [comment]
> Should I approve your changes?

It seems that commit 50c591eb41fca74f4bdfdf239a652fe544d98bbf (Move CoreExecutor code into CmdArgs) got lost during my rebase. I'll update my branch with the latest changes from main once more.

**Comment by frankschmitt** [comment]
@Verisimilitude11 Should be fine now - merge whenever it suits you :smile:

**Comment by Verisimilitude11** [comment]
> @Verisimilitude11 Should be fine now - merge whenever it suits you 😄

Sounds good, I'll merge it after doing some testing! Thanks for working on this!

**Pull request merged**
