### PR TITLE
Issue #237 renamed package DNAnalzer to dnanalyzer.

### LINKED ISSUE #237: JUnit Test skeleton doesn't work
Gradle can't find any tests to execute.
```
Execution failed for task ':test'.
No tests found for given includes: [DNAnalyzer.MainTest.mainClassshouldExist](--tests filter)
```

**To Reproduce**
Run tests inside class MainTest with Gradle (using IntelliJ)

**Expected behavior**
The one initially created test is executed correctly

### PR DESCRIPTION
**Pull request by MartinGallauner**
Closes #237 

Gradle ignores classes in packages with capital letters because they are against java naming conventions.

### CODE REVIEW

**Review by LimesKey — COMMENTED** [review]
Can you not just change it to "dnanalyzer" instead of just "analyzer", or even "dna_analyzer"? Analyzer is too generic, it needs to sound cool. As well, there's a branch conflict and 1 check that should be addressed; "Better Code Hub — ⚠️️ You lost 3 guidelines". I don't know what the check means but you can ask Verisimilitude.

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
Please don't change the name of the software everywhere using find and replace. Instead, just change the package declarations from `DNAnalyzer` to `dnanalyzer`

**Comment by MartinGallauner** [comment]
omg, I trusted IntelliJ that it will refactor only the package correctly.
I'm sorry!

**Comment by Verisimilitude11** [comment]
Don't worry @MartinGallauner, it happens to all of us! Your changes now look great - just one last thing. Could you please clear the merge conflicts associated with this PR: 
image
This will be a great learning experience getting to learn the git CLI. Let me know in the Discord server if you need any assistance with this. Thanks again for the PR, you're doing an awesome job!

**Comment by MartinGallauner** [comment]
Strange, I can't reproduce the merge conflict locally @Verisimilitude11

**Review by Verisimilitude11 — APPROVED** [review]
Looks great @MartinGallauner, congrats on getting your first PR merged in DNAnalyzer!

**Comment by MartinGallauner** [comment]
Nice, my very first open-source contribution :) 
Thank you for your patience @Verisimilitude11

**Review by Verisimilitude11 — APPROVED** [review]
Looks great, thanks for working on this!

**Pull request closed without merging**
