### PR TITLE
#76 refactor print protein list

### LINKED ISSUE #76: Refactor Properties.printProteinList(ArrayList,String)
I've selected [**Properties.printProteinList(ArrayList,String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/Properties.java#L35-L74) for refactoring, which is a unit of **33** lines of code and **20** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by Speedro**
closes #76 
Print protein list refatorings

### CODE REVIEW

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
image is this on purpose @Speedro?

**Comment by Verisimilitude11** [comment]
> image is this on purpose @Speedro?

The code looks great btw!

**Comment by Speedro** [comment]
> image is this on purpose @Speedro?
> 

oh damn, no sorry, thats a template I need to use for my work, for new files. Will get rid of that. 😅

**Review by Verisimilitude11 — APPROVED** [review]
Looks great, CodeScene marked the issue as resolved! I'll do some more testing later today and merge it.

**Review by Nv7-GitHub — COMMENTED** [review]
Looks good!

**Pull request merged**
