### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by ArchontisKostis**
I refactored the code because the Cyclomatic Complexity of this class (Properties.java) was too high (20 according to IntelliJ CodeMetrics plugin). 
For this reason I created some extra methods to reduce the complexity, improve readability and make the quality of the code better. I think now the code for this class is easier to understand, the class complexity was reduced to 8.

### CODE REVIEW

**Comment by Verisimilitude11** [comment]
This looks great @ArchontisKostis! However, I see that it fails CodeScene's Cloud Delta Analysis:
image
Could you try to fix them? If not, this looks fine anyway, I'll approve it. Thanks so much for contributing!

**Comment by ArchontisKostis** [comment]
Hello! Thanks for your review! I will check on it and try to fix it as soon as I can. If I won't be able to fix it I will comment here to inform you. 😊

**Comment by Verisimilitude11** [comment]
Sounds great! If it isn’t possible, don’t worry too much about it, I’ll approve/merge the PR.

**Comment by ArchontisKostis** [comment]
Hey! I really can't think of something to fix it right now. :(
So if you want accept the PR and we can make an issue for someone else to help!

**Comment by Verisimilitude11** [comment]
Sounds good, I'll approve the PR later today after some testing. In the meantime, could you please open an issue for this? Thanks!

**Comment by ArchontisKostis** [comment]
Great! Yes I will make an issue.
Thanks!

**Comment by ArchontisKostis** [comment]
Though I think it would be better to make the issue after the PR is accepted in order to not confuse anyone and avoid conflicts.
Else someone might fix things at the code before the refactoring and there might be a conflict.
If you agree of course.

**Comment by Verisimilitude11** [comment]
I think that it should be fine if you link this PR to the issue. Thanks for asking!

**Comment by ArchontisKostis** [comment]
Great! So when the PR gets accepted I will create an issue and link it here. I will also add the screenshot you added above. 😊😊

**Comment by Verisimilitude11** [comment]
@ArchontisKostis could you please resolve the conflicts? Thanks! I'll approve your PR tomorrow once that is done. Thanks for contributing, we really appreciate your time and help!

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
@ArchontisKostis it seems like there's a bug here:
image
(src\main\java\DNAnalyzer\Properties.java)

Could you please look into this? Thanks!

**Comment by Verisimilitude11** [comment]
@ArchontisKostis please resolve conflicts and fix the bugs that I mentioned earlier. Thanks!

**Comment by Verisimilitude11** [comment]
No worries @ArchontisKostis, it's fine.

**Comment by Verisimilitude11** [comment]
@ArchontisKostis could you please clear the conflicts?

**Comment by Verisimilitude11** [comment]
@ArchontisKostis another reminder to please resolve the merge conflicts.

**Review by Verisimilitude11 — APPROVED** [review]
Looks great! I apologize for the delay in reviewing it.

**Comment by Verisimilitude11** [comment]
> This looks great @ArchontisKostis! However, I see that it fails CodeScene's Cloud Delta Analysis: image Could you try to fix them? If not, this looks fine anyway, I'll approve it. Thanks so much for contributing!

@ArchontisKostis could you please create separate issues for this? Thanks!

**Pull request merged**
